apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: matomo
  template: matomo
message: |-
  Matomo Server has been scheduled for creation in your project, and should be soon available.
  N:B This Matomo template is vanilla template(non GDP compliant) which needs settings for GDPR-compliant analytics of your needs.

  * Username: ${MYSQL_USER}
  * Database Name: ${MYSQL_DATABASE}
  * Connection URL: mysql://${DATABASE_SERVICE_NAME}:3306/

  Building images takes some minutes to complete, so please be patient. You can follow progress on your projects overview page.
metadata:
  annotations:
    description: This template deploys Matomo Server with Mariadb.
    iconClass: fa fa-bar-chart
    openshift.io/display-name: Matomo
    openshift.io/documentation-url: https://github.com/CSCfi/matomo-openshift-template
    openshift.io/support-url: https://www.csc.fi/contact-info
    openshift.io/long-description: ""
    openshift.io/provider-display-name: CSC
    tags: mariadb,matomo
    template.openshift.io/bindable: "false"
  name: matomo

# Matomo objects

# Route
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${MATOMO_APP_NAME}
    name: ${MATOMO_APP_NAME}-route
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${MATOMO_APP_NAME}-svc
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    
#Secret
- apiVersion: v1
  stringData:
    matomo-username: ${MATOMO_USERNAME}
    matomo-password: ${MATOMO_PASSWORD}
    matomo-db-user: ${MATOMO_DATABASE_USER}
    matomo-db-password: ${MATOMO_DATABASE_PASSWORD}
    matomo-db-name: ${MATOMO_DATABASE_NAME}
  kind: Secret
  metadata:
    name: ${MATOMO_APP_NAME}-secret
  type: Opaque

# DeploymentConfig
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app:  ${MATOMO_APP_NAME}
      template: ${MATOMO_APP_NAME}-template
    name: ${MATOMO_APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${MATOMO_APP_NAME}
      deploymentconfig: ${MATOMO_APP_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app:  ${MATOMO_APP_NAME}
          deploymentconfig:  ${MATOMO_APP_NAME}
      spec:
        containers:
        - env:
            - name: MATOMO_USERNAME
              valueFrom:
                secretKeyRef:
                  key: matomo-username
                  name: ${MATOMO_APP_NAME}-secret
            - name: MATOMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: matomo-password
                  name: ${MATOMO_APP_NAME}-secret
            - name: MATOMO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: matomo-db-user
                  name: ${MATOMO_APP_NAME}-secret
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: matomo-db-password
                  name: ${MATOMO_APP_NAME}-secret
            - name: MATOMO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: matomo-db-name
                  name: ${MATOMO_APP_NAME}-secret
          image: bitnami/matomo:latest
          imagePullPolicy: Always
          name: matomo
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: ${MATOMO_APP_NAME}-data
            mountPath: "/etc/matomopass"
            readOnly: true
        volumes:
        - name: ${MATOMO_APP_NAME}-data
          secret:
            defaultMode: 420
            secretName: ${MATOMO_APP_NAME}-secret
# Service
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${MATOMO_APP_NAME}
    name: ${MATOMO_APP_NAME}-svc
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: ${MATOMO_APP_NAME}
    type: ClusterIP
  status:
    loadBalancer: {}

####################
# Matomo parameters
parameters:
- description: Unique identifier for your application. Recommended value - your username
  displayName: Application Name
  name: MATOMO_APP_NAME
  required: true
  value: matomo-app
- description: Username for logging into Matomo
  displayName: Username
  name: MATOMO_USERNAME
  required: true
- description: Password for logging into Matomo
  displayName: Pasword
  name: MATOMO_PASSWORD
  required: true
- description: Username for Matomo database user that will be used for accessing the database.
  displayName: Matomo MariaDB Connection Username
  name: MATOMO_DATABASE_USER
  required: true
  value: matomouser
- description: Password for the matomo MariaDB connection user.
  displayName: Matomo MariaDB Connection Password
  name: MATOMO_DATABASE_PASSWORD
  required: true
- description: Name of the matomo MariaDB database accessed.
  displayName: Matomo MariaDB Database Name
  name: MATOMO_DATABASE_NAME
  required: true
  value: matomodb
- description: Mariadb port number.
  displayName: Mariadb port number
  name: MARIADB_PORT_NUMBER
  required: true
  value: "3306"
- description: Mariadb host name.
  displayName: Mariadb host name
  name: MARIADB_HOST
  required: true
  value: mariadb
- description: Matomo proxy client header.
  displayName: Matomo proxy client header
  name: MATOMO_PROXY_CLIENT_HEADER
  required: true
  value: HTTP_X_FORWARDED_FOR
